// <auto-generated />
using System;
using CarAndAll.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarAndAll.Server.Migrations
{
    [DbContext(typeof(CarAndAllContext))]
    [Migration("20241205154323_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CarAndAll.Server.Models.Abonnement", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prijs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Type");

                    b.ToTable("Abonnementen");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Bedrijf", b =>
                {
                    b.Property<int>("KvkNummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbonnementType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("KvkNummer");

                    b.HasIndex("AbonnementType");

                    b.ToTable("Bedrijven");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Foto", b =>
                {
                    b.Property<int>("FotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedewerkerPersoneelsNummer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchademeldingID")
                        .HasColumnType("INTEGER");

                    b.HasKey("FotoID");

                    b.HasIndex("MedewerkerPersoneelsNummer");

                    b.HasIndex("SchademeldingID");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Gebruiker", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("Gebruiker");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Medewerker", b =>
                {
                    b.Property<int>("PersoneelsNummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("PersoneelsNummer");

                    b.HasIndex("PersoneelsNummer")
                        .IsUnique();

                    b.ToTable("Medewerkers");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Notitie", b =>
                {
                    b.Property<int>("NotitieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Inhoud")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("MedewerkerPersoneelsNummer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchademeldingID")
                        .HasColumnType("INTEGER");

                    b.HasKey("NotitieID");

                    b.HasIndex("MedewerkerPersoneelsNummer");

                    b.HasIndex("SchademeldingID");

                    b.ToTable("Notities");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Schademelding", b =>
                {
                    b.Property<int>("SchademeldingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("MedewerkerPersoneelsNummer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("VerhuuraanvraagAanvraagID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoertuigID")
                        .HasColumnType("INTEGER");

                    b.HasKey("SchademeldingID");

                    b.HasIndex("MedewerkerPersoneelsNummer");

                    b.HasIndex("VerhuuraanvraagAanvraagID");

                    b.HasIndex("VoertuigID");

                    b.ToTable("Schademeldingen");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Verhuuraanvraag", b =>
                {
                    b.Property<int>("AanvraagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EindDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("KlantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("VoertuigID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AanvraagID");

                    b.HasIndex("KlantId");

                    b.HasIndex("VoertuigID");

                    b.ToTable("Verhuuraanvragen");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Voertuig", b =>
                {
                    b.Property<int>("VoertuigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aanschafjaar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kenteken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("VoertuigID");

                    b.ToTable("Voertuigen");

                    b.HasData(
                        new
                        {
                            VoertuigID = -1,
                            Aanschafjaar = 2018,
                            Kenteken = "AB-123-CD",
                            Merk = "Toyota",
                            Soort = "auto",
                            Type = "Corolla"
                        },
                        new
                        {
                            VoertuigID = -2,
                            Aanschafjaar = 2019,
                            Kenteken = "EF-456-GH",
                            Merk = "Ford",
                            Soort = "auto",
                            Type = "Focus"
                        },
                        new
                        {
                            VoertuigID = -3,
                            Aanschafjaar = 2020,
                            Kenteken = "IJ-789-KL",
                            Merk = "Volkswagen",
                            Soort = "auto",
                            Type = "Golf"
                        },
                        new
                        {
                            VoertuigID = -4,
                            Aanschafjaar = 2017,
                            Kenteken = "MN-012-OP",
                            Merk = "Honda",
                            Soort = "auto",
                            Type = "Civic"
                        },
                        new
                        {
                            VoertuigID = -5,
                            Aanschafjaar = 2021,
                            Kenteken = "QR-345-ST",
                            Merk = "BMW",
                            Soort = "auto",
                            Type = "3 Serie"
                        },
                        new
                        {
                            VoertuigID = -6,
                            Aanschafjaar = 2016,
                            Kenteken = "UV-678-WX",
                            Merk = "Audi",
                            Soort = "auto",
                            Type = "A4"
                        },
                        new
                        {
                            VoertuigID = -7,
                            Aanschafjaar = 2022,
                            Kenteken = "YZ-901-AB",
                            Merk = "Mercedes",
                            Soort = "auto",
                            Type = "C-Klasse"
                        },
                        new
                        {
                            VoertuigID = -8,
                            Aanschafjaar = 2015,
                            Kenteken = "CD-234-EF",
                            Merk = "Nissan",
                            Soort = "auto",
                            Type = "Qashqai"
                        },
                        new
                        {
                            VoertuigID = -9,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-567-IJ",
                            Merk = "Peugeot",
                            Soort = "auto",
                            Type = "208"
                        },
                        new
                        {
                            VoertuigID = -10,
                            Aanschafjaar = 2018,
                            Kenteken = "KL-890-MN",
                            Merk = "Renault",
                            Soort = "auto",
                            Type = "Clio"
                        },
                        new
                        {
                            VoertuigID = -11,
                            Aanschafjaar = 2017,
                            Kenteken = "OP-123-QR",
                            Merk = "Hobby",
                            Soort = "auto",
                            Type = "De Luxe"
                        },
                        new
                        {
                            VoertuigID = -12,
                            Aanschafjaar = 2018,
                            Kenteken = "ST-456-UV",
                            Merk = "Fendt",
                            Soort = "auto",
                            Type = "Bianco"
                        },
                        new
                        {
                            VoertuigID = -13,
                            Aanschafjaar = 2019,
                            Kenteken = "WX-789-YZ",
                            Merk = "Knaus",
                            Soort = "auto",
                            Type = "Sport"
                        },
                        new
                        {
                            VoertuigID = -14,
                            Aanschafjaar = 2016,
                            Kenteken = "AB-012-CD",
                            Merk = "Dethleffs",
                            Soort = "auto",
                            Type = "Camper"
                        },
                        new
                        {
                            VoertuigID = -15,
                            Aanschafjaar = 2020,
                            Kenteken = "EF-345-GH",
                            Merk = "Adria",
                            Soort = "auto",
                            Type = "Altea"
                        },
                        new
                        {
                            VoertuigID = -16,
                            Aanschafjaar = 2015,
                            Kenteken = "IJ-678-KL",
                            Merk = "Eriba",
                            Soort = "auto",
                            Type = "Touring"
                        },
                        new
                        {
                            VoertuigID = -17,
                            Aanschafjaar = 2021,
                            Kenteken = "MN-901-OP",
                            Merk = "Tabbert",
                            Soort = "auto",
                            Type = "Puccini"
                        },
                        new
                        {
                            VoertuigID = -18,
                            Aanschafjaar = 2019,
                            Kenteken = "QR-234-ST",
                            Merk = "Burstner",
                            Soort = "auto",
                            Type = "Premio"
                        },
                        new
                        {
                            VoertuigID = -19,
                            Aanschafjaar = 2018,
                            Kenteken = "UV-567-WX",
                            Merk = "LMC",
                            Soort = "auto",
                            Type = "Musica"
                        },
                        new
                        {
                            VoertuigID = -20,
                            Aanschafjaar = 2022,
                            Kenteken = "YZ-890-AB",
                            Merk = "Sprite",
                            Soort = "auto",
                            Type = "Cruzer"
                        },
                        new
                        {
                            VoertuigID = -21,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-123-EF",
                            Merk = "Volkswagen",
                            Soort = "auto",
                            Type = "California"
                        },
                        new
                        {
                            VoertuigID = -22,
                            Aanschafjaar = 2019,
                            Kenteken = "GH-456-IJ",
                            Merk = "Mercedes",
                            Soort = "auto",
                            Type = "Marco Polo"
                        },
                        new
                        {
                            VoertuigID = -23,
                            Aanschafjaar = 2020,
                            Kenteken = "KL-789-MN",
                            Merk = "Ford",
                            Soort = "auto",
                            Type = "Nugget"
                        },
                        new
                        {
                            VoertuigID = -24,
                            Aanschafjaar = 2017,
                            Kenteken = "OP-012-QR",
                            Merk = "Fiat",
                            Soort = "auto",
                            Type = "Ducato"
                        },
                        new
                        {
                            VoertuigID = -25,
                            Aanschafjaar = 2021,
                            Kenteken = "ST-345-UV",
                            Merk = "Citroen",
                            Soort = "auto",
                            Type = "Jumper"
                        },
                        new
                        {
                            VoertuigID = -26,
                            Aanschafjaar = 2016,
                            Kenteken = "WX-678-YZ",
                            Merk = "Peugeot",
                            Soort = "auto",
                            Type = "Boxer"
                        },
                        new
                        {
                            VoertuigID = -27,
                            Aanschafjaar = 2022,
                            Kenteken = "AB-901-CD",
                            Merk = "Renault",
                            Soort = "auto",
                            Type = "Master"
                        },
                        new
                        {
                            VoertuigID = -28,
                            Aanschafjaar = 2015,
                            Kenteken = "EF-234-GH",
                            Merk = "Iveco",
                            Soort = "auto",
                            Type = "Daily"
                        },
                        new
                        {
                            VoertuigID = -29,
                            Aanschafjaar = 2021,
                            Kenteken = "IJ-567-KL",
                            Merk = "Opel",
                            Soort = "auto",
                            Type = "Movano"
                        },
                        new
                        {
                            VoertuigID = -30,
                            Aanschafjaar = 2018,
                            Kenteken = "MN-890-OP",
                            Merk = "Nissan",
                            Soort = "auto",
                            Type = "NV400"
                        },
                        new
                        {
                            VoertuigID = -31,
                            Aanschafjaar = 2019,
                            Kenteken = "QR-123-ST",
                            Merk = "Kia",
                            Soort = "auto",
                            Type = "Sportage"
                        },
                        new
                        {
                            VoertuigID = -32,
                            Aanschafjaar = 2020,
                            Kenteken = "UV-456-WX",
                            Merk = "Hyundai",
                            Soort = "auto",
                            Type = "Tucson"
                        },
                        new
                        {
                            VoertuigID = -33,
                            Aanschafjaar = 2017,
                            Kenteken = "YZ-789-AB",
                            Merk = "Skoda",
                            Soort = "auto",
                            Type = "Octavia"
                        },
                        new
                        {
                            VoertuigID = -34,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-012-EF",
                            Merk = "Mazda",
                            Soort = "auto",
                            Type = "3"
                        },
                        new
                        {
                            VoertuigID = -35,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-345-IJ",
                            Merk = "Subaru",
                            Soort = "auto",
                            Type = "Impreza"
                        },
                        new
                        {
                            VoertuigID = -36,
                            Aanschafjaar = 2019,
                            Kenteken = "KL-678-MN",
                            Merk = "Suzuki",
                            Soort = "auto",
                            Type = "Vitara"
                        },
                        new
                        {
                            VoertuigID = -37,
                            Aanschafjaar = 2020,
                            Kenteken = "OP-901-QR",
                            Merk = "Volvo",
                            Soort = "auto",
                            Type = "XC60"
                        },
                        new
                        {
                            VoertuigID = -38,
                            Aanschafjaar = 2017,
                            Kenteken = "ST-234-UV",
                            Merk = "Mitsubishi",
                            Soort = "auto",
                            Type = "Outlander"
                        },
                        new
                        {
                            VoertuigID = -39,
                            Aanschafjaar = 2022,
                            Kenteken = "WX-567-YZ",
                            Merk = "Jeep",
                            Soort = "auto",
                            Type = "Wrangler"
                        },
                        new
                        {
                            VoertuigID = -40,
                            Aanschafjaar = 2021,
                            Kenteken = "YZ-890-AB",
                            Merk = "Land Rover",
                            Soort = "auto",
                            Type = "Defender"
                        },
                        new
                        {
                            VoertuigID = -41,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-123-EF",
                            Merk = "Bailey",
                            Soort = "auto",
                            Type = "Unicorn"
                        },
                        new
                        {
                            VoertuigID = -42,
                            Aanschafjaar = 2019,
                            Kenteken = "GH-456-IJ",
                            Merk = "Lunar",
                            Soort = "auto",
                            Type = "Clubman"
                        },
                        new
                        {
                            VoertuigID = -43,
                            Aanschafjaar = 2020,
                            Kenteken = "KL-789-MN",
                            Merk = "Swi",
                            Soort = "auto",
                            Type = "Conqueror"
                        },
                        new
                        {
                            VoertuigID = -44,
                            Aanschafjaar = 2017,
                            Kenteken = "OP-012-QR",
                            Merk = "Elddis",
                            Soort = "auto",
                            Type = "Avante"
                        },
                        new
                        {
                            VoertuigID = -45,
                            Aanschafjaar = 2021,
                            Kenteken = "ST-345-UV",
                            Merk = "Compass",
                            Soort = "auto",
                            Type = "Casita"
                        },
                        new
                        {
                            VoertuigID = -46,
                            Aanschafjaar = 2016,
                            Kenteken = "WX-678-YZ",
                            Merk = "Coachman",
                            Soort = "auto",
                            Type = "VIP"
                        },
                        new
                        {
                            VoertuigID = -47,
                            Aanschafjaar = 2016,
                            Kenteken = "WX-678-YZ",
                            Merk = "Coachman",
                            Soort = "auto",
                            Type = "VIP"
                        },
                        new
                        {
                            VoertuigID = -48,
                            Aanschafjaar = 2022,
                            Kenteken = "AB-901-CD",
                            Merk = "Buccaneer",
                            Soort = "auto",
                            Type = "Commodore"
                        },
                        new
                        {
                            VoertuigID = -49,
                            Aanschafjaar = 2015,
                            Kenteken = "EF-234-GH",
                            Merk = "Caravelair",
                            Soort = "auto",
                            Type = "Allegra"
                        },
                        new
                        {
                            VoertuigID = -50,
                            Aanschafjaar = 2021,
                            Kenteken = "IJ-567-KL",
                            Merk = "Sterckeman",
                            Soort = "auto",
                            Type = "Starlett"
                        },
                        new
                        {
                            VoertuigID = -51,
                            Aanschafjaar = 2018,
                            Kenteken = "MN-890-OP",
                            Merk = "Tab",
                            Soort = "auto",
                            Type = "320"
                        },
                        new
                        {
                            VoertuigID = -52,
                            Aanschafjaar = 2019,
                            Kenteken = "QR-123-ST",
                            Merk = "Volkswagen",
                            Soort = "auto",
                            Type = "Grand California"
                        },
                        new
                        {
                            VoertuigID = -53,
                            Aanschafjaar = 2020,
                            Kenteken = "UV-456-WX",
                            Merk = "Mercedes",
                            Soort = "auto",
                            Type = "Sprinter"
                        },
                        new
                        {
                            VoertuigID = -54,
                            Aanschafjaar = 2017,
                            Kenteken = "YZ-789-AB",
                            Merk = "Ford",
                            Soort = "auto",
                            Type = "Transit Custom"
                        },
                        new
                        {
                            VoertuigID = -55,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-012-EF",
                            Merk = "Fiat",
                            Soort = "auto",
                            Type = "Scudo"
                        },
                        new
                        {
                            VoertuigID = -56,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-345-IJ",
                            Merk = "Citroen",
                            Soort = "auto",
                            Type = "Berlingo"
                        },
                        new
                        {
                            VoertuigID = -57,
                            Aanschafjaar = 2019,
                            Kenteken = "WX-678-YZ",
                            Merk = "Peugeot",
                            Soort = "auto",
                            Type = "Partner"
                        },
                        new
                        {
                            VoertuigID = -58,
                            Aanschafjaar = 2020,
                            Kenteken = "AB-901-CD",
                            Merk = "Renault",
                            Soort = "auto",
                            Type = "Kangoo"
                        },
                        new
                        {
                            VoertuigID = -59,
                            Aanschafjaar = 2017,
                            Kenteken = "EF-234-GH",
                            Merk = "Iveco",
                            Soort = "auto",
                            Type = "Eurocargo"
                        },
                        new
                        {
                            VoertuigID = -60,
                            Aanschafjaar = 2022,
                            Kenteken = "IJ-567-KL",
                            Merk = "Opel",
                            Soort = "auto",
                            Type = "Combo"
                        },
                        new
                        {
                            VoertuigID = -61,
                            Aanschafjaar = 2021,
                            Kenteken = "MN-890-OP",
                            Merk = "Nissan",
                            Soort = "auto",
                            Type = "NV200"
                        },
                        new
                        {
                            VoertuigID = -62,
                            Aanschafjaar = 2018,
                            Kenteken = "QR-123-ST",
                            Merk = "Kia",
                            Soort = "auto",
                            Type = "Picanto"
                        },
                        new
                        {
                            VoertuigID = -63,
                            Aanschafjaar = 2019,
                            Kenteken = "UV-456-WX",
                            Merk = "Hyundai",
                            Soort = "auto",
                            Type = "i30"
                        },
                        new
                        {
                            VoertuigID = -64,
                            Aanschafjaar = 2020,
                            Kenteken = "YZ-789-AB",
                            Merk = "Skoda",
                            Soort = "auto",
                            Type = "Superb"
                        },
                        new
                        {
                            VoertuigID = -65,
                            Aanschafjaar = 2017,
                            Kenteken = "CD-012-EF",
                            Merk = "Mazda",
                            Soort = "auto",
                            Type = "6"
                        },
                        new
                        {
                            VoertuigID = -66,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-345-IJ",
                            Merk = "Subaru",
                            Soort = "auto",
                            Type = "Forester"
                        },
                        new
                        {
                            VoertuigID = -67,
                            Aanschafjaar = 2019,
                            Kenteken = "KL-678-MN",
                            Merk = "Suzuki",
                            Soort = "auto",
                            Type = "Swift"
                        },
                        new
                        {
                            VoertuigID = -68,
                            Aanschafjaar = 2020,
                            Kenteken = "OP-901-QR",
                            Merk = "Volvo",
                            Soort = "auto",
                            Type = "XC90"
                        },
                        new
                        {
                            VoertuigID = -69,
                            Aanschafjaar = 2017,
                            Kenteken = "ST-234-UV",
                            Merk = "Mitsubishi",
                            Soort = "auto",
                            Type = "Eclipse Cross"
                        },
                        new
                        {
                            VoertuigID = -70,
                            Aanschafjaar = 2022,
                            Kenteken = "WX-567-YZ",
                            Merk = "Jeep",
                            Soort = "auto",
                            Type = "Renegade"
                        },
                        new
                        {
                            VoertuigID = -71,
                            Aanschafjaar = 2021,
                            Kenteken = "YZ-890-AB",
                            Merk = "Land Rover",
                            Soort = "auto",
                            Type = "Discovery"
                        },
                        new
                        {
                            VoertuigID = -72,
                            Aanschafjaar = 2018,
                            Kenteken = "AB-123-CD",
                            Merk = "Volkswagen",
                            Soort = "camper",
                            Type = "California"
                        },
                        new
                        {
                            VoertuigID = -73,
                            Aanschafjaar = 2019,
                            Kenteken = "EF-456-GH",
                            Merk = "Mercedes",
                            Soort = "camper",
                            Type = "Marco Polo"
                        },
                        new
                        {
                            VoertuigID = -74,
                            Aanschafjaar = 2020,
                            Kenteken = "IJ-789-KL",
                            Merk = "Ford",
                            Soort = "camper",
                            Type = "Transit Custom"
                        },
                        new
                        {
                            VoertuigID = -75,
                            Aanschafjaar = 2017,
                            Kenteken = "MN-012-OP",
                            Merk = "Fiat",
                            Soort = "camper",
                            Type = "Ducato"
                        },
                        new
                        {
                            VoertuigID = -76,
                            Aanschafjaar = 2021,
                            Kenteken = "QR-345-ST",
                            Merk = "Citroën",
                            Soort = "camper",
                            Type = "Jumper"
                        },
                        new
                        {
                            VoertuigID = -77,
                            Aanschafjaar = 2016,
                            Kenteken = "UV-678-WX",
                            Merk = "Peugeot",
                            Soort = "camper",
                            Type = "Boxer"
                        },
                        new
                        {
                            VoertuigID = -78,
                            Aanschafjaar = 2022,
                            Kenteken = "YZ-901-AB",
                            Merk = "Renault",
                            Soort = "camper",
                            Type = "Master"
                        },
                        new
                        {
                            VoertuigID = -79,
                            Aanschafjaar = 2015,
                            Kenteken = "CD-234-EF",
                            Merk = "Nissan",
                            Soort = "camper",
                            Type = "NV400"
                        },
                        new
                        {
                            VoertuigID = -80,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-567-IJ",
                            Merk = "Opel",
                            Soort = "camper",
                            Type = "Movano"
                        },
                        new
                        {
                            VoertuigID = -81,
                            Aanschafjaar = 2018,
                            Kenteken = "KL-890-MN",
                            Merk = "Iveco",
                            Soort = "camper",
                            Type = "Daily"
                        },
                        new
                        {
                            VoertuigID = -82,
                            Aanschafjaar = 2017,
                            Kenteken = "OP-123-QR",
                            Merk = "Volkswagen",
                            Soort = "camper",
                            Type = "Grand California"
                        },
                        new
                        {
                            VoertuigID = -83,
                            Aanschafjaar = 2019,
                            Kenteken = "ST-456-UV",
                            Merk = "Mercedes",
                            Soort = "camper",
                            Type = "Sprinter"
                        },
                        new
                        {
                            VoertuigID = -84,
                            Aanschafjaar = 2020,
                            Kenteken = "WX-789-YZ",
                            Merk = "Ford",
                            Soort = "camper",
                            Type = "Nugget"
                        },
                        new
                        {
                            VoertuigID = -85,
                            Aanschafjaar = 2016,
                            Kenteken = "AB-012-CD",
                            Merk = "Fiat",
                            Soort = "camper",
                            Type = "Talento"
                        },
                        new
                        {
                            VoertuigID = -86,
                            Aanschafjaar = 2018,
                            Kenteken = "EF-345-GH",
                            Merk = "Citroën",
                            Soort = "camper",
                            Type = "SpaceTourer"
                        },
                        new
                        {
                            VoertuigID = -87,
                            Aanschafjaar = 2021,
                            Kenteken = "IJ-678-KL",
                            Merk = "Peugeot",
                            Soort = "camper",
                            Type = "Traveller"
                        },
                        new
                        {
                            VoertuigID = -88,
                            Aanschafjaar = 2020,
                            Kenteken = "MN-901-OP",
                            Merk = "Renault",
                            Soort = "camper",
                            Type = "Trafic"
                        },
                        new
                        {
                            VoertuigID = -89,
                            Aanschafjaar = 2019,
                            Kenteken = "QR-234-ST",
                            Merk = "Nissan",
                            Soort = "camper",
                            Type = "Primastar"
                        },
                        new
                        {
                            VoertuigID = -90,
                            Aanschafjaar = 2022,
                            Kenteken = "UV-567-WX",
                            Merk = "Opel",
                            Soort = "camper",
                            Type = "Vivaro"
                        },
                        new
                        {
                            VoertuigID = -91,
                            Aanschafjaar = 2017,
                            Kenteken = "YZ-890-AB",
                            Merk = "Iveco",
                            Soort = "camper",
                            Type = "Eurocargo"
                        },
                        new
                        {
                            VoertuigID = -92,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-123-EF",
                            Merk = "Volkswagen",
                            Soort = "camper",
                            Type = "Mul van"
                        },
                        new
                        {
                            VoertuigID = -93,
                            Aanschafjaar = 2020,
                            Kenteken = "GH-456-IJ",
                            Merk = "Mercedes",
                            Soort = "camper",
                            Type = "Vito"
                        },
                        new
                        {
                            VoertuigID = -94,
                            Aanschafjaar = 2017,
                            Kenteken = "KL-789-MN",
                            Merk = "Ford",
                            Soort = "camper",
                            Type = "Kuga Camper"
                        },
                        new
                        {
                            VoertuigID = -95,
                            Aanschafjaar = 2018,
                            Kenteken = "OP-012-QR",
                            Merk = "Fiat",
                            Soort = "camper",
                            Type = "Scudo"
                        },
                        new
                        {
                            VoertuigID = -96,
                            Aanschafjaar = 2019,
                            Kenteken = "ST-345-UV",
                            Merk = "Citroën",
                            Soort = "camper",
                            Type = "Berlingo"
                        },
                        new
                        {
                            VoertuigID = -97,
                            Aanschafjaar = 2016,
                            Kenteken = "WX-678-YZ",
                            Merk = "Peugeot",
                            Soort = "camper",
                            Type = "Expert Camper"
                        },
                        new
                        {
                            VoertuigID = -98,
                            Aanschafjaar = 2022,
                            Kenteken = "AB-901-CD",
                            Merk = "Renault",
                            Soort = "camper",
                            Type = "Kangoo Camper"
                        },
                        new
                        {
                            VoertuigID = -99,
                            Aanschafjaar = 2015,
                            Kenteken = "EF-234-GH",
                            Merk = "Nissan",
                            Soort = "camper",
                            Type = "Juke Camper"
                        },
                        new
                        {
                            VoertuigID = -100,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-567-IJ",
                            Merk = "Opel",
                            Soort = "camper",
                            Type = "Zafira Camper"
                        },
                        new
                        {
                            VoertuigID = -101,
                            Aanschafjaar = 2018,
                            Kenteken = "KL-890-MN",
                            Merk = "Iveco",
                            Soort = "camper",
                            Type = "Camper 2000"
                        },
                        new
                        {
                            VoertuigID = -102,
                            Aanschafjaar = 2017,
                            Kenteken = "OP-123-QR",
                            Merk = "Volkswagen",
                            Soort = "camper",
                            Type = "Kombi"
                        },
                        new
                        {
                            VoertuigID = -103,
                            Aanschafjaar = 2021,
                            Kenteken = "ST-456-UV",
                            Merk = "Mercedes",
                            Soort = "camper",
                            Type = "Sprinter XXL"
                        },
                        new
                        {
                            VoertuigID = -104,
                            Aanschafjaar = 2020,
                            Kenteken = "WX-789-YZ",
                            Merk = "Ford",
                            Soort = "camper",
                            Type = "Custom Camper"
                        },
                        new
                        {
                            VoertuigID = -105,
                            Aanschafjaar = 2016,
                            Kenteken = "AB-012-CD",
                            Merk = "Fiat",
                            Soort = "camper",
                            Type = "Ducato Maxi"
                        },
                        new
                        {
                            VoertuigID = -106,
                            Aanschafjaar = 2018,
                            Kenteken = "EF-345-GH",
                            Merk = "Citroën",
                            Soort = "camper",
                            Type = "Jumper Camper"
                        },
                        new
                        {
                            VoertuigID = -107,
                            Aanschafjaar = 2021,
                            Kenteken = "IJ-678-KL",
                            Merk = "Peugeot",
                            Soort = "camper",
                            Type = "Boxer XL"
                        },
                        new
                        {
                            VoertuigID = -108,
                            Aanschafjaar = 2019,
                            Kenteken = "MN-901-OP",
                            Merk = "Renault",
                            Soort = "camper",
                            Type = "Master Pro"
                        },
                        new
                        {
                            VoertuigID = -109,
                            Aanschafjaar = 2022,
                            Kenteken = "QR-234-ST",
                            Merk = "Nissan",
                            Soort = "camper",
                            Type = "NV300 Camper"
                        },
                        new
                        {
                            VoertuigID = -110,
                            Aanschafjaar = 2017,
                            Kenteken = "UV-567-WX",
                            Merk = "Opel",
                            Soort = "camper",
                            Type = "Vivaro XL"
                        },
                        new
                        {
                            VoertuigID = -111,
                            Aanschafjaar = 2018,
                            Kenteken = "YZ-890-AB",
                            Merk = "Iveco",
                            Soort = "camper",
                            Type = "Daily Pro"
                        },
                        new
                        {
                            VoertuigID = -112,
                            Aanschafjaar = 2020,
                            Kenteken = "CD-123-EF",
                            Merk = "Volkswagen",
                            Soort = "camper",
                            Type = "T6 California"
                        },
                        new
                        {
                            VoertuigID = -113,
                            Aanschafjaar = 2019,
                            Kenteken = "GH-456-IJ",
                            Merk = "Mercedes",
                            Soort = "camper",
                            Type = "V-Class Camper"
                        },
                        new
                        {
                            VoertuigID = -114,
                            Aanschafjaar = 2022,
                            Kenteken = "KL-789-MN",
                            Merk = "Ford",
                            Soort = "camper",
                            Type = "Transit Nugget Plus"
                        },
                        new
                        {
                            VoertuigID = -115,
                            Aanschafjaar = 2018,
                            Kenteken = "AB-123-CD",
                            Merk = "Hobby",
                            Soort = "caravan",
                            Type = "De Luxe"
                        },
                        new
                        {
                            VoertuigID = -116,
                            Aanschafjaar = 2019,
                            Kenteken = "EF-456-GH",
                            Merk = "Fendt",
                            Soort = "caravan",
                            Type = "Bianco"
                        },
                        new
                        {
                            VoertuigID = -117,
                            Aanschafjaar = 2020,
                            Kenteken = "IJ-789-KL",
                            Merk = "Knaus",
                            Soort = "caravan",
                            Type = "Sport"
                        },
                        new
                        {
                            VoertuigID = -118,
                            Aanschafjaar = 2017,
                            Kenteken = "MN-012-OP",
                            Merk = "Adria",
                            Soort = "caravan",
                            Type = "Altea"
                        },
                        new
                        {
                            VoertuigID = -119,
                            Aanschafjaar = 2021,
                            Kenteken = "QR-345-ST",
                            Merk = "Dethleffs",
                            Soort = "caravan",
                            Type = "Camper"
                        },
                        new
                        {
                            VoertuigID = -120,
                            Aanschafjaar = 2016,
                            Kenteken = "UV-678-WX",
                            Merk = "Tabbert",
                            Soort = "caravan",
                            Type = "Puccini"
                        },
                        new
                        {
                            VoertuigID = -121,
                            Aanschafjaar = 2022,
                            Kenteken = "YZ-901-AB",
                            Merk = "Burstner",
                            Soort = "caravan",
                            Type = "Premio"
                        },
                        new
                        {
                            VoertuigID = -122,
                            Aanschafjaar = 2015,
                            Kenteken = "CD-234-EF",
                            Merk = "LMC",
                            Soort = "caravan",
                            Type = "Musica"
                        },
                        new
                        {
                            VoertuigID = -123,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-567-IJ",
                            Merk = "Sprite",
                            Soort = "caravan",
                            Type = "Cruzer"
                        },
                        new
                        {
                            VoertuigID = -124,
                            Aanschafjaar = 2018,
                            Kenteken = "KL-890-MN",
                            Merk = "Bailey",
                            Soort = "caravan",
                            Type = "Unicorn"
                        },
                        new
                        {
                            VoertuigID = -125,
                            Aanschafjaar = 2017,
                            Kenteken = "OP-123-QR",
                            Merk = "Lunar",
                            Soort = "caravan",
                            Type = "Clubman"
                        },
                        new
                        {
                            VoertuigID = -126,
                            Aanschafjaar = 2019,
                            Kenteken = "ST-456-UV",
                            Merk = "Swi",
                            Soort = "caravan",
                            Type = "Conqueror"
                        },
                        new
                        {
                            VoertuigID = -127,
                            Aanschafjaar = 2020,
                            Kenteken = "WX-789-YZ",
                            Merk = "Compass",
                            Soort = "caravan",
                            Type = "Casita"
                        },
                        new
                        {
                            VoertuigID = -128,
                            Aanschafjaar = 2016,
                            Kenteken = "AB-012-CD",
                            Merk = "Coachman",
                            Soort = "caravan",
                            Type = "VIP"
                        },
                        new
                        {
                            VoertuigID = -129,
                            Aanschafjaar = 2018,
                            Kenteken = "EF-345-GH",
                            Merk = "Buccaneer",
                            Soort = "caravan",
                            Type = "Commodore"
                        },
                        new
                        {
                            VoertuigID = -130,
                            Aanschafjaar = 2021,
                            Kenteken = "IJ-678-KL",
                            Merk = "Caravelair",
                            Soort = "caravan",
                            Type = "Allegra"
                        },
                        new
                        {
                            VoertuigID = -131,
                            Aanschafjaar = 2020,
                            Kenteken = "MN-901-OP",
                            Merk = "Sterckeman",
                            Soort = "caravan",
                            Type = "Starle"
                        },
                        new
                        {
                            VoertuigID = -132,
                            Aanschafjaar = 2019,
                            Kenteken = "QR-234-ST",
                            Merk = "Tab",
                            Soort = "caravan",
                            Type = "320"
                        },
                        new
                        {
                            VoertuigID = -133,
                            Aanschafjaar = 2022,
                            Kenteken = "UV-567-WX",
                            Merk = "Eriba",
                            Soort = "caravan",
                            Type = "Touring"
                        },
                        new
                        {
                            VoertuigID = -134,
                            Aanschafjaar = 2017,
                            Kenteken = "YZ-890-AB",
                            Merk = "Adria",
                            Soort = "caravan",
                            Type = "Ac on"
                        },
                        new
                        {
                            VoertuigID = -135,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-123-EF",
                            Merk = "Fendt",
                            Soort = "caravan",
                            Type = "Tendenza"
                        },
                        new
                        {
                            VoertuigID = -136,
                            Aanschafjaar = 2020,
                            Kenteken = "GH-456-IJ",
                            Merk = "Knaus",
                            Soort = "caravan",
                            Type = "Sudwind"
                        },
                        new
                        {
                            VoertuigID = -137,
                            Aanschafjaar = 2017,
                            Kenteken = "KL-789-MN",
                            Merk = "Hobby",
                            Soort = "caravan",
                            Type = "Excellent"
                        },
                        new
                        {
                            VoertuigID = -138,
                            Aanschafjaar = 2019,
                            Kenteken = "OP-012-QR",
                            Merk = "Dethleffs",
                            Soort = "caravan",
                            Type = "Beduin"
                        },
                        new
                        {
                            VoertuigID = -139,
                            Aanschafjaar = 2021,
                            Kenteken = "ST-345-UV",
                            Merk = "Burstner",
                            Soort = "caravan",
                            Type = "Averso"
                        },
                        new
                        {
                            VoertuigID = -140,
                            Aanschafjaar = 2020,
                            Kenteken = "WX-678-YZ",
                            Merk = "LMC",
                            Soort = "caravan",
                            Type = "Vivo"
                        },
                        new
                        {
                            VoertuigID = -141,
                            Aanschafjaar = 2019,
                            Kenteken = "AB-901-CD",
                            Merk = "Sprite",
                            Soort = "caravan",
                            Type = "Major"
                        },
                        new
                        {
                            VoertuigID = -142,
                            Aanschafjaar = 2022,
                            Kenteken = "EF-234-GH",
                            Merk = "Bailey",
                            Soort = "caravan",
                            Type = "Phoenix"
                        },
                        new
                        {
                            VoertuigID = -143,
                            Aanschafjaar = 2017,
                            Kenteken = "GH-567-IJ",
                            Merk = "Lunar",
                            Soort = "caravan",
                            Type = "Delta"
                        },
                        new
                        {
                            VoertuigID = -144,
                            Aanschafjaar = 2018,
                            Kenteken = "KL-890-MN",
                            Merk = "Swi",
                            Soort = "caravan",
                            Type = "Elegance"
                        },
                        new
                        {
                            VoertuigID = -145,
                            Aanschafjaar = 2021,
                            Kenteken = "OP-123-QR",
                            Merk = "Compass",
                            Soort = "caravan",
                            Type = "Corona"
                        },
                        new
                        {
                            VoertuigID = -146,
                            Aanschafjaar = 2019,
                            Kenteken = "ST-456-UV",
                            Merk = "Coachman",
                            Soort = "caravan",
                            Type = "Acadia"
                        },
                        new
                        {
                            VoertuigID = -147,
                            Aanschafjaar = 2020,
                            Kenteken = "WX-789-YZ",
                            Merk = "Buccaneer",
                            Soort = "caravan",
                            Type = "Barracuda"
                        },
                        new
                        {
                            VoertuigID = -148,
                            Aanschafjaar = 2016,
                            Kenteken = "AB-012-CD",
                            Merk = "Caravelair",
                            Soort = "caravan",
                            Type = "Antares"
                        },
                        new
                        {
                            VoertuigID = -149,
                            Aanschafjaar = 2018,
                            Kenteken = "EF-345-GH",
                            Merk = "Sterckeman",
                            Soort = "caravan",
                            Type = "Evolu on"
                        },
                        new
                        {
                            VoertuigID = -150,
                            Aanschafjaar = 2021,
                            Kenteken = "IJ-678-KL",
                            Merk = "Tab",
                            Soort = "caravan",
                            Type = "400"
                        },
                        new
                        {
                            VoertuigID = -151,
                            Aanschafjaar = 2020,
                            Kenteken = "MN-901-OP",
                            Merk = "Eriba",
                            Soort = "caravan",
                            Type = "Nova"
                        },
                        new
                        {
                            VoertuigID = -152,
                            Aanschafjaar = 2019,
                            Kenteken = "QR-234-ST",
                            Merk = "Adria",
                            Soort = "caravan",
                            Type = "Adora"
                        },
                        new
                        {
                            VoertuigID = -153,
                            Aanschafjaar = 2022,
                            Kenteken = "UV-567-WX",
                            Merk = "Fendt",
                            Soort = "caravan",
                            Type = "Opal"
                        },
                        new
                        {
                            VoertuigID = -154,
                            Aanschafjaar = 2017,
                            Kenteken = "YZ-890-AB",
                            Merk = "Knaus",
                            Soort = "caravan",
                            Type = "Sky Traveller"
                        },
                        new
                        {
                            VoertuigID = -155,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-123-EF",
                            Merk = "Hobby",
                            Soort = "caravan",
                            Type = "Pres ge"
                        },
                        new
                        {
                            VoertuigID = -156,
                            Aanschafjaar = 2020,
                            Kenteken = "GH-456-IJ",
                            Merk = "Dethleffs",
                            Soort = "caravan",
                            Type = "C'go"
                        },
                        new
                        {
                            VoertuigID = -157,
                            Aanschafjaar = 2017,
                            Kenteken = "KL-789-MN",
                            Merk = "Burstner",
                            Soort = "caravan",
                            Type = "Premio Life"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Klant", b =>
                {
                    b.HasBaseType("CarAndAll.Server.Models.Gebruiker");

                    b.Property<string>("AbonnementType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BedrijfKvkNummer")
                        .HasColumnType("INTEGER");

                    b.HasIndex("AbonnementType");

                    b.HasIndex("BedrijfKvkNummer");

                    b.HasDiscriminator().HasValue("Klant");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Bedrijf", b =>
                {
                    b.HasOne("CarAndAll.Server.Models.Abonnement", "Abonnement")
                        .WithMany()
                        .HasForeignKey("AbonnementType");

                    b.Navigation("Abonnement");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Foto", b =>
                {
                    b.HasOne("CarAndAll.Server.Models.Medewerker", "Medewerker")
                        .WithMany("Fotos")
                        .HasForeignKey("MedewerkerPersoneelsNummer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarAndAll.Server.Models.Schademelding", "Schademelding")
                        .WithMany("Fotos")
                        .HasForeignKey("SchademeldingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medewerker");

                    b.Navigation("Schademelding");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Notitie", b =>
                {
                    b.HasOne("CarAndAll.Server.Models.Medewerker", "Medewerker")
                        .WithMany("Notities")
                        .HasForeignKey("MedewerkerPersoneelsNummer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarAndAll.Server.Models.Schademelding", "Schademelding")
                        .WithMany("Notities")
                        .HasForeignKey("SchademeldingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medewerker");

                    b.Navigation("Schademelding");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Schademelding", b =>
                {
                    b.HasOne("CarAndAll.Server.Models.Medewerker", "Medewerker")
                        .WithMany("Schademeldingen")
                        .HasForeignKey("MedewerkerPersoneelsNummer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarAndAll.Server.Models.Verhuuraanvraag", "Verhuuraanvraag")
                        .WithMany("Schademeldingen")
                        .HasForeignKey("VerhuuraanvraagAanvraagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarAndAll.Server.Models.Voertuig", "Voertuig")
                        .WithMany("Schademeldingen")
                        .HasForeignKey("VoertuigID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medewerker");

                    b.Navigation("Verhuuraanvraag");

                    b.Navigation("Voertuig");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Verhuuraanvraag", b =>
                {
                    b.HasOne("CarAndAll.Server.Models.Klant", "Klant")
                        .WithMany("Verhuuraanvraagen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarAndAll.Server.Models.Voertuig", "Voertuig")
                        .WithMany("Verhuuraanvragen")
                        .HasForeignKey("VoertuigID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klant");

                    b.Navigation("Voertuig");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CarAndAll.Server.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CarAndAll.Server.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarAndAll.Server.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CarAndAll.Server.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Klant", b =>
                {
                    b.HasOne("CarAndAll.Server.Models.Abonnement", null)
                        .WithMany("Klanten")
                        .HasForeignKey("AbonnementType");

                    b.HasOne("CarAndAll.Server.Models.Bedrijf", "Bedrijf")
                        .WithMany("Klanten")
                        .HasForeignKey("BedrijfKvkNummer");

                    b.Navigation("Bedrijf");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Abonnement", b =>
                {
                    b.Navigation("Klanten");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Bedrijf", b =>
                {
                    b.Navigation("Klanten");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Medewerker", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Notities");

                    b.Navigation("Schademeldingen");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Schademelding", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Notities");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Verhuuraanvraag", b =>
                {
                    b.Navigation("Schademeldingen");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Voertuig", b =>
                {
                    b.Navigation("Schademeldingen");

                    b.Navigation("Verhuuraanvragen");
                });

            modelBuilder.Entity("CarAndAll.Server.Models.Klant", b =>
                {
                    b.Navigation("Verhuuraanvraagen");
                });
#pragma warning restore 612, 618
        }
    }
}
